// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechChallenge.Infrastructure.Repository.ApplicationDbContext;

#nullable disable

namespace TechChallenge.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240724105113_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechChallenge.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<int>("RegionDDD")
                        .HasColumnType("INT");

                    b.HasKey("Guid");

                    b.HasIndex("RegionDDD");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("TechChallenge.Domain.Entities.Region", b =>
                {
                    b.Property<int>("DDD")
                        .HasColumnType("INT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("DDD");

                    b.ToTable("Region", (string)null);
                });

            modelBuilder.Entity("TechChallenge.Domain.Entities.Contact", b =>
                {
                    b.HasOne("TechChallenge.Domain.Entities.Region", "Region")
                        .WithMany("Contacts")
                        .HasForeignKey("RegionDDD")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Contact_Region");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TechChallenge.Domain.Entities.Region", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
