apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      name: mssql
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
          envFrom:
            - configMapRef:
                name: config-map-mssql          
            - secretRef:
                name: secret-ms-mssql
                optional: true
          volumeMounts:
            - name: mssql-volume
              mountPath: "/var/opt/mssql"
      volumes:
        - name: mssql-volume
          hostPath:
          persistentVolumeClaim:
            claimName: mssql-pvc
          # livenessProbe:
          #   httpGet:
          #     path: /api/1
          #     port: 80
          #   initialDelaySeconds: 180
          #   periodSeconds: 60
          # readnessProbe:
          #   httpGet:
          #     path: /api/1
          #     port: 80
          # ports:
          #   - containerPort: 80
          # resources:
          #   limits:
          #     cpu: 2
          #     ephemeral-storage: 1Gi
          #     memory: 8Gi
          #   requests:
          #     cpu: 2
          #     ephemeral-storage: 1Gi
          #     memory: 8Gi

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: mssql
  name: mssql-sv
spec:
  ports:
  - protocol: TCP
    name: app
    port: 1433 
    targetPort: 1433
    nodePort: 31433 
  selector:
    app: mssql
  type: NodePort

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: hostpath