{
 "title": "Tech Challange Endpoints Microservice",
 "description": "Tech Challange Endpoints Microservice metrics from OpenTelemetry",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Duration - POST - api/contacts/creation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,  sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate - POST api/contacts/creation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\", http_response_status_code=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\", http_response_status_code=~\"4..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-creation\", instance=\"host.docker-internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-creation\", instance=\"hots.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\", http_response_status_code=~\"5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code - post",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n    max_over_time(http_server_request_duration_seconds_count{http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[$__rate_interval])\r\n  )",
     "legendFormat": "Status {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests Secured - get",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol - get",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"contact-creation\", instance=\"host.docker.internal:8090\", http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Requests Duration - GET - api/contacts/search",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,  sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate - GET api/contacts/search",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\", http_response_status_code=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\", http_response_status_code=~\"4..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker-internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"hots.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\", http_response_status_code=~\"5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code - get",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n    max_over_time(http_server_request_duration_seconds_count{http_route=\"api/contacts/search\", http_request_method=\"GET\"}[$__rate_interval])\r\n  )",
     "legendFormat": "Status {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests Secured - get",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol - get",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Requests Duration - GET - api/contacts/search/{ddd:int}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,  sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate - GET - api/contacts/search/{ddd:int}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\", http_response_status_code=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\", http_response_status_code=~\"4..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-seach\", instance=\"host.docker-internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"hots.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\", http_response_status_code=~\"5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code - get ddd",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n    max_over_time(http_server_request_duration_seconds_count{http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[$__rate_interval])\r\n  )",
     "legendFormat": "Status {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests Secured - get ddd",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol - get ddd",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"contact-search\", instance=\"host.docker.internal:8092\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Requests Duration - PUT - api/contacts/update",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,  sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/api/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate - PUT - api/contacts/update",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\", http_response_status_code=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\", http_response_status_code=~\"4..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-update\", instance=\"host.docker-internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-update\", instance=\"hots.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\", http_response_status_code=~\"5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code - update",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-update\", instance=\"host.docker.internal:8091\",http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[$__rate_interval])\r\n  )",
     "legendFormat": "Status {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests Secured - update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP - update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"contact-update\", instance=\"host.docker.internal:8091\", http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Requests Duration - DELETE - api/contacts/delete",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,  sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate - DELETE - api/contacts/delete",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\", http_response_status_code=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\", http_response_status_code=~\"4..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-delete\", instance=\"host.docker-internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-delete\", instance=\"hots.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\", http_response_status_code=~\"5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code - delete",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-delete\", instance=\"host.docker.internal:8093\",http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[$__rate_interval])\r\n  )",
     "legendFormat": "Status {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests Secured - delete",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP - delete",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"contact-delete\", instance=\"host.docker.internal:8093\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  }
 ]
}