{
 "title": "Docker Registry",
 "tags": [
  "docker",
  "registry",
  "internals"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "query_result(registry_http_in_flight_requests)"
   },
   {
    "name": "app",
    "query": "query_result(registry_http_in_flight_requests{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "query": "query_result(up{app=\"$app\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "description": "start time of the process",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_start_time_seconds{app=\"$app\", instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Total Cache Requests",
   "type": "singlestat",
   "description": "The number of cache request received",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "registry_storage_cache_total{instance=\"$instance\",type=\"Request\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Total Hit Cache Requests",
   "type": "singlestat",
   "description": "The number of cache request received (hits)",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "registry_storage_cache_total{instance=\"$instance\",type=\"Hit\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Total Missed Cache Requests",
   "type": "singlestat",
   "description": "The number of cache request received (miss)",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "registry_storage_cache_total{instance=\"$instance\",type=\"Miss\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "singlestat",
   "description": "Process Resident Memory Usage",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"$instance\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{instance=\"$instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Registry Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "The HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(registry_http_requests_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "In-Flight HTTP Requests",
   "type": "graph",
   "description": "The in-flight HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "registry_http_in_flight_requests{instance=\"$instance\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Registry Cache Requests Rate",
   "type": "graph",
   "description": "The rate of registry cache requests",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(registry_storage_cache_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Registry Action Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(registry_storage_action_seconds_sum{instance=\"$instance\"}[2m]) * 1000",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "HTTP Request Latencies in seconds (blob)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob\"}[10m])"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (base)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"base\"}[10m])"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (blob_upload)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob_upload\"}[10m])"
    }
   ]
  },
  {
   "title": "Manifest HTTP Request Latencies in seconds (manifest)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"manifest\"}[10m])"
    }
   ]
  },
  {
   "title": "Catalog HTTP Request Latencies in seconds (catalog)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"catalog\"}[10m])"
    }
   ]
  }
 ]
}
{
 "title": "Tech Challange Endpoints Microservice",
 "description": "Tech Challange Endpoints Microservice metrics from OpenTelemetry",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Duration - POST - api/contacts/creation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,  sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate - POST api/contacts/creation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\", http_response_status_code=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\", http_response_status_code=~\"4..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\", http_response_status_code=~\"5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code - post",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n    max_over_time(http_server_request_duration_seconds_count{http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[$__rate_interval])\r\n  )",
     "legendFormat": "Status {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests Secured - get",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol - get",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"contact-creation\",  http_route=\"api/contacts/creation\", http_request_method=\"POST\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Requests Duration - GET - api/contacts/search",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,  sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate - GET api/contacts/search",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\", http_response_status_code=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\", http_response_status_code=~\"4..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\",  http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\",  http_route=\"api/contacts/search\", http_request_method=\"GET\", http_response_status_code=~\"5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code - get",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n    max_over_time(http_server_request_duration_seconds_count{http_route=\"api/contacts/search\", http_request_method=\"GET\"}[$__rate_interval])\r\n  )",
     "legendFormat": "Status {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests Secured - get",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol - get",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"contact-search\", http_route=\"api/contacts/search\", http_request_method=\"GET\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Requests Duration - GET - api/contacts/search/{ddd:int}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,  sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate - GET - api/contacts/search/{ddd:int}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\", http_response_status_code=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\", http_response_status_code=~\"4..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-seach\",  http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\",  http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\", http_response_status_code=~\"5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code - get ddd",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n    max_over_time(http_server_request_duration_seconds_count{http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[$__rate_interval])\r\n  )",
     "legendFormat": "Status {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests Secured - get ddd",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol - get ddd",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"contact-search\", http_route=\"api/contacts/search/{ddd:int}\", http_request_method=\"GET\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Requests Duration - PUT - api/contacts/update",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,  sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate - PUT - api/contacts/update",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\", http_response_status_code=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\", http_response_status_code=~\"4..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\", http_response_status_code=~\"5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code - update",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-update\", http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[$__rate_interval])\r\n  )",
     "legendFormat": "Status {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests Secured - update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP - update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"contact-update\",  http_route=\"api/contacts/update\", http_request_method=\"PUT\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Requests Duration - DELETE - api/contacts/delete",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,  sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate - DELETE - api/contacts/delete",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\", http_response_status_code=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\", http_response_status_code=~\"4..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\", http_response_status_code=~\"5..\"}[5m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_count{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code - delete",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-delete\", http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[$__rate_interval])\r\n  )",
     "legendFormat": "Status {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests Secured - delete",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    max_over_time(http_server_request_duration_seconds_count{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP - delete",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"contact-delete\",  http_route=\"api/contacts/delete/{guid:Guid}\", http_request_method=\"DELETE\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  }
 ]
}