apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-controller
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-controller
  template:
    metadata:
      name: search-controller
      labels:
        app: search-controller
    spec:
      containers:
        - name: search-controller
          image: ronanavila/search-controller
          env:
          envFrom:
            - configMapRef:
                name: config-map-search-controller          
            - secretRef:
                name: secret-ms-search-controller
                optional: true

          # livenessProbe:
          #   httpGet:
          #     path: /api/1
          #     port: 80
          #   initialDelaySeconds: 180
          #   periodSeconds: 60
          # readnessProbe:
          #   httpGet:
          #     path: /api/1
          #     port: 80
          # ports:
          #   - containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: search-controller
  name: search-controller-sv
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31200
  selector:
    app: search-controller
  type: NodePort

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-search-controller
  labels:
    app: search  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-controller
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # behavior:
  #   scaleDown:
  #     policies:
  #     - type: Percent
  #       value: 10
  #       periodSeconds: 10