apiVersion: apps/v1
kind: Deployment
metadata:
  name: creation-consumer
  labels:
    app: creation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creation-consumer
  template:
    metadata:
      name: creation-consumer
      labels:
        app: creation-consumer
    spec:
      containers:
        - name: creation-consumer
          image: ronanavila/creation-consumer
          env:
          envFrom:
            - configMapRef:
                name: config-map-creation-consumer          
            - secretRef:
                name: secret-ms-creation-consumer
                optional: true

          # livenessProbe:
          #   httpGet:
          #     path: /api/1
          #     port: 80
          #   initialDelaySeconds: 180
          #   periodSeconds: 60
          # readnessProbe:
          #   httpGet:
          #     path: /api/1
          #     port: 80
          # ports:
          #   - containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-creation-consumer
  labels:
    app: creation  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: creation-consumer
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # behavior:
  #   scaleDown:
  #     policies:
  #     - type: Percent
  #       value: 10
  #       periodSeconds: 10
